services:
    sqldb:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: app_db
        ports:
         - 8002:1433
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=StrongP@ss1
        networks:
          - multidbcontext

    aspire-dashboard:
        image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
        environment:
           DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
            - Otlp__Enabled=true
            - Otlp__Endpoint=http://+:18888
        ports:
          - 18888:18888
          - 18889:18889
        
        networks:
          - multidbcontext
networks:
  multidbcontext:
    driver: bridge
            