services:
 rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq
    restart: unless-stopped

networks:
  rabbitmq:
    driver: bridge  
    