// <auto-generated />
using EFCoreApi.Data;
using EFCoreApi.Data.Optimized;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
